services:
  nginx:
    image: ${IMG_REGISTRY:-bybatkhuu}/nginx:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      - "./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/sites-enabled"
      - "./volumes/storage/nginx/configs/templates:/etc/nginx/templates"
      - "./volumes/storage/nginx/www:/var/www"
      - "./volumes/storage/nginx/logs:/var/log/nginx"
    network_mode: host
    tty: true
