services:
  nginx:
    image: bybatkhuu/nginx:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/storage/nginx/logs:/var/log/nginx"
      - "./volumes/storage/nginx/www:/var/www"
      - "./volumes/storage/nginx/configs/sites-enabled:/etc/nginx/sites-enabled"
      - "./volumes/storage/nginx/configs/templates:/etc/nginx/templates"
    network_mode: host
    tty: true
