version: "3.8"

services:
  nginx:
    image: ${NGINX_IMG_NAMESCAPE:-bybatkhuu}/nginx:${NGINX_IMG_VERSION:-latest}
    build:
      context: .
    restart: unless-stopped
    environment:
      - TERM=${TERM:-xterm}
      - TZ=${TZ:-Asia/Seoul}
    volumes:
      - "./volumes/storage/nginx/configs/templates:/etc/nginx/templates"
      - "./volumes/storage/nginx/logs:/var/log/nginx"
    network_mode: host
    tty: true
