services:
  nginx:
    # env_file:
    #   - .env
    volumes:
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      # - "./volumes/storage/nginx/ssl:/etc/nginx/ssl"
      - "./volumes/.vscode-server:/root/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 1G
    # network_mode: bridge
    # ports:
    #   - "${NGINX_HTTPS_PORT:-443}:${NGINX_HTTPS_PORT:-443}"
    #   - "${NGINX_HTTP_PORT:-80}:${NGINX_HTTP_PORT:-80}"
    # command: ["--https=self"]
    # command: ["--https=valid"]
    # command: ["--https=lets"]
    # command: ["/bin/bash"]
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${NGINX_HTTP_PORT:-80}"]
    #   start_period: 15s
    #   start_interval: 1s
    #   interval: 5m
    #   timeout: 5s
    #   retries: 3
